### PR TITLE
Revert "Disable AVR targets on macOS due to homebrew issue"

### PR DESCRIPTION
**Pull request by yamt**
Reverts apache/incubator-nuttx-testing#85

### CODE REVIEW

**Comment by yamt** [comment]
let's see if the fix for https://github.com/osx-cross/homebrew-avr/issues/205 works for us

**Comment by btashton** [comment]
@yamt looks like the brew upgrade hits this bug 
https://github.com/actions/virtual-environments/issues/2322

Current recommendation from GitHub is to first `rm -rf /usr/local/bin/2to3`

**Comment by yamt** [comment]
I looked at the log of macOS "other" job. it looks ok.

**Comment by btashton** [comment]
What do you think about doing `brew update --quiet` instead to cut down the log spam? Do you think we should move that command and 2to3 fix to the start since it is not really avr specific?

**Comment by yamt** [comment]
i didn't know it has --quiet option.

i don't know if it's avr-gcc specific or not. i assumed it wasn't. but i might be wrong.

**Pull request merged**
