### PR TITLE
docker: update mips toolchain comments info

### PR DESCRIPTION
**Pull request by liuguo09**
Signed-off-by: liuhaitao <liuhaitao@xiaomi.com>

### CODE REVIEW

**Comment by btashton** [comment]
Looks good.  I have a few more changes to make to the image to get all the builds working correctly against, the sim target seems to have been relying on some apt recommended packages not just the ones listed, so I am tracking those down and will have them ready shortly.

**Comment by liuguo09** [comment]
@btashton Thanks. I see push image step not run when merged. Do we need update workflow with such as 'if: github.event.pull_request.merged == true'?

**Comment by btashton** [comment]
@liuguo09 It is doing the correct thing.  You will see it on the commit in master, in this case
https://github.com/apache/incubator-nuttx-testing/runs/526369392

**Comment by liuguo09** [comment]
Get it. Thanks let me know.

**Pull request merged**
