### PR TITLE
Add x86_64 to the test lists

### PR DESCRIPTION
**Pull request by btashton**
Add x86_64 to the test lists

### CODE REVIEW

**Comment by btashton** [comment]
Need to figure out how to get the
macOS builds to use gcc instead of clang

**Comment by xiaoxiang781216** [comment]
> Need to figure out how to get the
> macOS builds to use gcc instead of clang

@yamt fix the similar issue, here is the patch:
```
commit 748777e3f5f61ccadefac19c0e32b25c13475e44
Author: YAMAMOTO Takashi <yamamoto@midokura.com>
Date:   Thu Mar 26 11:28:08 2020 +0900

    sim: MODULE definitions for macOS

diff --git a/boards/sim/sim/sim/configs/cxxtest/Make.defs b/boards/sim/sim/sim/configs/cxxtest/Make.defs
index 633eed8e9e..dfab86026c 100644
--- a/boards/sim/sim/sim/configs/cxxtest/Make.defs
+++ b/boards/sim/sim/sim/configs/cxxtest/Make.defs
@@ -86,6 +86,18 @@ else
   LDMODULEFLAGS += -T $(TOPDIR)/libs/libc/modlib/gnu-elf.ld
 endif
 
+# NuttX modules are ELF binaries.
+# Non-ELF platforms like macOS need to use a separate ELF toolchain.
+ifeq ($(CONFIG_HOST_MACOS),y)
+  # eg. brew install x86_64-elf-gcc
+  MODULECC = x86_64-elf-gcc
+  MODULELD = x86_64-elf-ld
+  # It seems macOS/x86_64 loads the program text around 00000001_xxxxxxxx.
+  # The gcc default (-mcmodel=small) would produce out-of-range 32-bit
+  # relocations.
+  CMODULEFLAGS += -mcmodel=large
+endif
+
```

**Comment by btashton** [comment]
@xiaoxiang781216 I had forgotten about this.  Just pushed PR that I think should resolve this in the main OS repository, thanks for the pointer.

**Comment by xiaoxiang781216** [comment]
@btashton still hit the build break.:(

**Comment by xiaoxiang781216** [comment]
@btashton still fail:(.

**Comment by btashton** [comment]
Verified that https://github.com/apache/incubator-nuttx/pull/1162 will make this pass

**Pull request merged**
