### PR TITLE
Switch to Ubuntu LTS 20.04 relaese for base image

### PR DESCRIPTION
**Pull request by btashton**
## Summary
Switch to Ubuntu LTS 20.10 relaese for base image

## Impact
Moving to the latest LTS release from a 19.10 non LTS release.

### CODE REVIEW

**Comment by v01d** [comment]
Hey Brennan, note that in your PR and commit message you are referring to 20.10 LTS which is in fact 20.04 LTS (the change correctly refers to 20.04 anyway).

**Comment by btashton** [comment]
Thanks I'll fix the commit when I figure out what's up with the build.

**Comment by btashton** [comment]
I have all the other build fixes in, but  Renesas GCC build seems to fail on 20.04
```
utf8 "\x92" does not map to Unicode at /usr/share/texinfo/Texinfo/ParserNonXS.pm line 1796, <FH> line 18418.
Malformed UTF-8 character: \x92 (unexpected continuation byte 0x92, with no preceding start byte) in pattern match (m//) at /usr/share/texinfo/Texinfo/ParserNonXS.pm line 3364.
Malformed UTF-8 character (fatal) at /usr/share/texinfo/Texinfo/ParserNonXS.pm line 3364.
make[2]: *** [Makefile:4353: doc/gcc.info] Error 38
```

**Comment by btashton** [comment]
@ramya-n-s I would like to move us to Ubuntu 20.04 for the base image, but I am running into some issues building the Renesas GCC build due to texinfo issues, do you have thoughts on this or would it be acceptable to move to a more modern version of GCC. I see that they list a 8.3.0 version as recommended.
https://gcc-renesas.com/rx-download-toolchains/

**Comment by ramya-n-s** [comment]
> @ramya-n-s I would like to move us to Ubuntu 20.04 for the base image, but I am running into some issues building the Renesas GCC build due to texinfo issues, do you have thoughts on this or would it be acceptable to move to a more modern version of GCC. I see that they list a 8.3.0 version as recommended.
> https://gcc-renesas.com/rx-download-toolchains/

Sorry for the delayed response. The texinfo version might be updated in the ubuntu 20.04 and it changed the default input encoding. So, it was required to set the input encoding at "gcc.texi" file. This issue can be fixed by appending the below command in the Dockerfile after line no 185,
sed -i '1s/^/@documentencoding ISO-8859-1\n/' ./gcc/doc/gcc.texi && \

**Comment by btashton** [comment]
@ramya-n-s Much appreciated, I was hoping I would not have to dig into the depths of textinfo. Looks like it is building now.

**Pull request merged**
