### PR TITLE
CI workflow from https://github.com/apache/incubator-nuttx

### PR DESCRIPTION
**Pull request by yamt**

### CODE REVIEW

**Comment by liuguo09** [comment]
Looks good to me. It's reasonable to do check build for testing. So make sure cibuild scripts and testlist update do not build break nuttx&apps CI.

**Comment by yamt** [comment]
does anyone have concerns on this?
i want to enable macOS builds based on this. https://github.com/apache/incubator-nuttx-testing/pull/23

**Comment by btashton** [comment]
I am fine with this.  I think through repo_dispatch events we can actually keep the workflows in this repo and have tiny dispatch ones in the others, but this will take a little more work.  For now lets just try to keep them all in sync starting with PRs against this one.

**Comment by btashton** [comment]
See this action for what I am thinking https://github.com/peter-evans/repository-dispatch

**Pull request merged**
