### PR TITLE
WIP: Fix avr ci on macOS

### PR DESCRIPTION
**Pull request by btashton**
## Summary
Something broke with the macOS avr toolchain in CI.

### CODE REVIEW

**Comment by yamt** [comment]
thank you for taking a look at this.
i suspect the very recent changes in their repo. https://github.com/osx-cross/homebrew-avr/commits/master

**Comment by btashton** [comment]
@yamt  I could not get this to install correctly.  When I manually fixed the path issue I got the same issue as running earlier versions with some library no being able to be loaded.  There is a ticket for this on there repo as well.  For now I have opened #85 to just disable AVR on macOS for now.  Can you take a look?
```
dyld: Library not loaded: /usr/local/opt/isl/lib/libisl.22.dylib 
```

**Comment by yamt** [comment]
@btashton i will take a look when i have time. hopefully someone in the upstream can fix it in the meantime. :-)

**Comment by btashton** [comment]
> @btashton i will take a look when i have time. hopefully someone in the upstream can fix it in the meantime. :-)

They said it was resolved today you could probably revert my commit. Having power issues this evening unfortunately otherwise I would kick off a build, if you want to give that a try we can see if it builds.

**Pull request closed without merging**
