### PR TITLE
Enable all renesas/rx65n config for all.dat and other.dat

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
## Summary
and sync up all.dat with other.dat

## Impact
Build more renesas config

## Testing
Pass CI

### CODE REVIEW

**Comment by v01d** [comment]
It seems some renesas Makefile needs updating: `/github/workspace/sources/nuttx/tools/testbuild.sh: line 252: /github/workspace/sources/nuttx/../nuttx/nuttx.manifest: No such file or directory
`

**Comment by xiaoxiang781216** [comment]
Done. need merge https://github.com/apache/incubator-nuttx/pull/3309 first.

**Comment by v01d** [comment]
Seems rx65n has quite a few issues

**Comment by xiaoxiang781216** [comment]
Yes, I will try to resolve the issue in nuttx repo.

**Pull request closed without merging**
